# Site settings
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://shugelei.github.io/ # the base hostname & protocol for your site

# User settings
 
title: Shuge Lei
email: slei@email.sc.edu
group: AISys
groupweb: https://pooyanjamshidi.github.io/AISys/
dept: Computing Science and Engineering
deptweb: https://cse.sc.edu/
institution: University of South Carolina
institutionweb: https://www.sc.edu/
address: Storey Innovation Center
addressweb: https://www.cse.sc.edu/contact
twitter: ShugeLei
github: Shugelei

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 3
paginate_path: /news/page:num/
excerpt_separator: <!--more-->

# Site-wide variables
keywords: python, deep learning, transfer learning, machine learning system, compiler, static analysis
copyright: Copyright (c) Shuge Lei

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate
#  - jemoji
